import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import firsat from "./imgs/firsat.svg"
import firsat2 from "./imgs/firsat2.svg"
import firsat3 from "./imgs/firsat3.svg"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div  className='flex justify-around text-xs text-grey-600'>
            <div>Bize Ulaşın</div>
            <div>İade Süreci</div>
            <div>Siparişlerim</div>
            <div className='flex w-4 h-4'>
            <Image src={firsat}/> 
              <div>Fırsatlar</div>
            </div>
            
            <div className='flex w-4 h-4'>
            <Image src={firsat2}/>
            <div className=" flex text-pink-500">Satış Yapın!</div>
            </div>
            <div className='flex w-4 h-4'>
            <Image src={firsat3}/>
            <div className=" flex text-blue-600">Favorilerim</div>
            </div>
            
        </div>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <hr></hr>

      
        <div className='flex justify-around text-xs text-grey-600'>
          <div className="m-4 p-4">Elektronik</div>
          <div  className="m-4 p-4">Anne Bebek</div>
          <div  className="m-4 p-4">Cep telefonu ve Aksesuar</div>
          <div className="m-4 p-4">Ev,Yaşam,Yapı Market</div>
          <div className="m-4 p-4">Ayakkabı, Çanta</div>
          <div className="m-4 p-4">Kitap,Kırtasiye,Hobi,Oyuncak</div>
          <div className="m-4 p-4">Kişisel Bakım ve Kozmetik</div>
          <div className="m-4 p-4">Moda</div>
          <div className="m-4 p-4">Otomobil,Motorsiklet</div>
          <div className="m-4 p-4">Oyun,Konsol ve Dijital Servisler</div>
        </div>
        <hr></hr>
        {children}
      </body>
    </html>
  );
}
